

services:
    rabbitmq:
      build:
        context: ./compose/rabbitmq
      hostname: rabbitmq
      ports:
        - "5672:5672"
        - "15672:15672"
  
    celery_worker_periodic:
        build: .
        command: "celery -A app worker --loglevel INFO"

    celery_worker_rate_limited:
        build: .
        command: "celery -A app worker --loglevel INFO -Q queue_for_simple_single_task_worker --pool=prefork --concurrency=1"

    celery_worker_beat:
        build: .
        command: "celery -A app beat --loglevel INFO"
